name: reskit
channels:
  - conda-forge
dependencies:
  # - python
  # - pytest
  # - pytest-cov
  # - pylint
  # - autopep8
  # - jupyter
  # - notebook
  # - jupyterlab
  - pip
  - matplotlib
  - descartes
  - pandas
  - numpy <=1.23.5
  - scipy
  - scikit-learn
  - gdal >2.2.0,<3.0.0
  - netCDF4 >=1.5.3
  - xarray
  - pvlib-python >=0.7.2,<=0.9.9
  - geokit
