[lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`) codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.

ignore = [
    "F401", # imported but unused
    "F405", # Variable is undefined or from star import
    "F403", #  `from test.helpers import *` used; unable to detect undefined names
    "F811", # Redefinition of unused variable
    "F541", # f-string without any placeholders
    "F841", # variable is assigned to but never used
    "F821", # Undefined name `plt`
    "E711", # Comparison to `None` should be `is None`
    "E712", # Avoid equality comparisons to `False`; use `not l1 == l3:` for false checks
    "E713", # Test for membership should be `not in`
    "E714", # [*] Test for object identity should be `is not`
    "E741", # Ambiguous variable name: `l`
    "E722", # Do not use bare `except`
]
